[package]
name = "hgen"
version = "0.5.0"
edition = "2021"
description = "API schema language for humans"
license = "MIT"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
console = "0.15.8"
pest = "2.7.10"
pest_derive = "2.7.10"
