// AUTOGENERATED FILE - DO NOT EDIT

import 'todo.external.dart';


typedef UUID = String;

class Todo {
  UUID id;
  String title;
  Instant createdAt;
  Instant? checkedAt;

  Todo({
    required this.id,
    required this.title,
    required this.createdAt,
    this.checkedAt,
  });

  Map<String, dynamic> toJson() => $TodoToJson(this);
  factory Todo.fromJson(Map<String, dynamic> json) => $TodoFromJson(json);
}

class CreateTodo {
  String title;

  CreateTodo({
    required this.title,
  });

  Map<String, dynamic> toJson() => $CreateTodoToJson(this);
  factory CreateTodo.fromJson(Map<String, dynamic> json) => $CreateTodoFromJson(json);
}

/* Map<String, dynamic> $InstantToJson(Instant instance) => ? */
dynamic $UUIDToJson(UUID instance) => instance;
Map<String, dynamic> $TodoToJson(Todo instance) => <String, dynamic>{'id':$UUIDToJson(instance.id),'title':instance.title,'createdAt':$InstantToJson(instance.createdAt),'checkedAt':instance.checkedAt == null ? null : $InstantToJson(instance.checkedAt as Instant)};
Map<String, dynamic> $CreateTodoToJson(CreateTodo instance) => <String, dynamic>{'title':instance.title};

/* Instant $InstantFromJson(Map<String, dynamic> json) => ? */
UUID $UUIDFromJson(dynamic json) => json as String;
Todo $TodoFromJson(Map<String,dynamic>json)=>Todo(id:$UUIDFromJson(json['id']),title:json['title'] as String,createdAt:$InstantFromJson(json['createdAt']),checkedAt:json['checkedAt'] == null ? null : $InstantFromJson(json['checkedAt']));
CreateTodo $CreateTodoFromJson(Map<String,dynamic>json)=>CreateTodo(title:json['title'] as String);
