// AUTOGENERATED FILE - DO NOT EDIT

import { Instant } from './todo.external';

export type UUID = string & {
  type: 'uuid'
};

export class Todo {
  id: UUID;
  title: string;
  createdAt: Instant;
  checkedAt: (Instant | null);
}

export class CreateTodo {
  title: string;
}

// prettier-ignore
export const $metadata = {'Instant':{type:'External',inner:{type:'String'}},'UUID':{type:'Alias',inner:{type:'String'}},'Todo':{type:'Struct',fields:{'id':{type:'Reference',name:'UUID'},'title':{type:'String'},'createdAt':{type:'Reference',name:'Instant'},'checkedAt':{type:'Nullable',inner:{type:'Reference',name:'Instant'}}}},'CreateTodo':{type:'Struct',fields:{'title':{type:'String'}}}} as const;
