// AUTOGENERATED FILE - DO NOT EDIT

import 'todo.external.dart';

class Todo {
  UUID id;
  String title;
  Instant createdAt;
  Instant? checkedAt;

  Todo({
    required this.id,
    required this.title,
    required this.createdAt,
    this.checkedAt,
  });

  Map<String, dynamic> toJson() => $TodoToJson(this);
  factory Todo.fromJson(Map<String, dynamic> json) => $TodoFromJson(json);
}

class UpdateTodoParams {
  String? title;

  UpdateTodoParams({
    this.title,
  });

  Map<String, dynamic> toJson() => $UpdateTodoParamsToJson(this);
  factory UpdateTodoParams.fromJson(Map<String, dynamic> json) => $UpdateTodoParamsFromJson(json);
}


class CreateTodoParams {
  String title;

  CreateTodoParams({
    required this.title,
  });

  Map<String, dynamic> toJson() => $CreateTodoParamsToJson(this);
  factory CreateTodoParams.fromJson(Map<String, dynamic> json) => $CreateTodoParamsFromJson(json);
}

typedef UUID = String;

Map<String, dynamic> $TodoToJson(Todo instance) => <String, dynamic>{'id':$UUIDToJson(instance.id),'title':instance.title,'createdAt':$InstantToJson(instance.createdAt),'checkedAt':instance.checkedAt == null ? null : $InstantToJson(instance.checkedAt as Instant)};
Map<String, dynamic> $UpdateTodoParamsToJson(UpdateTodoParams instance) => <String, dynamic>{'title':instance.title == null ? null : instance.title as String};
/* Map<String, dynamic> $InstantToJson(Instant instance) => ? */
Map<String, dynamic> $CreateTodoParamsToJson(CreateTodoParams instance) => <String, dynamic>{'title':instance.title};
dynamic $UUIDToJson(UUID instance) => instance;

Todo $TodoFromJson(Map<String,dynamic>json)=>Todo(id:$UUIDFromJson(json['id']),title:json['title'] as String,createdAt:$InstantFromJson(json['createdAt']),checkedAt:json['checkedAt'] == null ? null : $InstantFromJson(json['checkedAt']));
UpdateTodoParams $UpdateTodoParamsFromJson(Map<String,dynamic>json)=>UpdateTodoParams(title:json['title'] == null ? null : json['title'] as String);
/* Instant $InstantFromJson(Map<String, dynamic> json) => ? */
CreateTodoParams $CreateTodoParamsFromJson(Map<String,dynamic>json)=>CreateTodoParams(title:json['title'] as String);
UUID $UUIDFromJson(dynamic json) => json as String;
