// AUTOGENERATED FILE - DO NOT EDIT

export class Post {
  slug: string;
  title: string;
  body: string;
  author: string;
}

export class PrivatePostServiceConsumer {
  constructor(
    protected request: (method: string, inputs: any) => Promise<any>
  ) {}

  create(slug: string, title: string, body: string): Promise<Post> {
    return this.request("create", { slug, title, body });
  }

  delete(slug: string): Promise<void> {
    return this.request("delete", { slug });
  }
}

export interface PrivatePostServiceProvider {
  create(slug: string, title: string, body: string): Promise<Post>;

  delete(slug: string): Promise<void>;
}

// prettier-ignore
export const $schema = {models:{Post:{type:'struct',fields:{slug:{type:'string',data:{}},title:{type:'string',data:{}},body:{type:'string',data:{}},author:{type:'string',data:{}}}}},services:{PrivatePostService:{type:'service',methods:{create:{inputs:{slug:{type:'string',data:{}},title:{type:'string',data:{}},body:{type:'string',data:{}}},output:{type:'reference',name:'Post',data:{}}},delete:{inputs:{slug:{type:'string',data:{}}},output:{type:'unit',data:{}}}}}}} as const;