// AUTOGENERATED FILE - DO NOT EDIT

export class Post {
  slug: string;
  title: string;
  body: string;
  author: string;
}

export class PrivatePostServiceConsumer {
  constructor(
    protected request: (method: string, inputs: any) => Promise<any>
  ) {}

  create(slug: string, title: string, body: string): Promise<Post> {
    return this.request("create", { slug, title, body });
  }

  delete(slug: string): Promise<void> {
    return this.request("delete", { slug });
  }
}

export interface PrivatePostServiceProvider {
  create(slug: string, title: string, body: string): Promise<Post>;

  delete(slug: string): Promise<void>;
}

// prettier-ignore
export const $schema = {models:{Post:{type:'Struct',fields:{slug:{type:'String'},title:{type:'String'},body:{type:'String'},author:{type:'String'}}}},services:{PrivatePostService:{type:'Service',methods:{create:{inputs:{slug:{type:'String'},title:{type:'String'},body:{type:'String'}},output:{type:'Reference',name:'Post'}},delete:{inputs:{slug:{type:'String'}},output:{type:'Unit'}}}}}} as const;